### ISSUE TITLE
Bug of #1 : ManagedExecutorService cannot be injected into the server endpoint POJO

### ISSUE THREAD

**Issue by rxue** [rxue/java8-finance#2]
**Error in the backend log** when sending request to http:localhost:8080/investment/prices.xhtml

	19:20:23,437 ERROR [io.undertow.websockets.core.request] (default task-2) UT025007: Unhandled exception for annotated endpoint rx.investment.StockPriceMonitor@5c4c88d1: java.lang.NullPointerException: Cannot invoke "jakarta.enterprise.concurrent.ManagedExecutorService.execute(java.lang.Runnable)" because "this.executor" is null
		at deployment.investment.war//rx.investment.StockPriceMonitor.repeatSend(StockPriceMonitor.java:24)
		at deployment.investment.war//rx.investment.StockPriceMonitor.open(StockPriceMonitor.java:21)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.base/java.lang.reflect.Method.invoke(Method.java:568)
		at io.undertow.websocket@2.3.0.Final//io.undertow.websockets.jsr.annotated.BoundMethod.invoke(BoundMethod.java:87)
		at io.undertow.websocket@2.3.0.Final//io.undertow.websockets.jsr.annotated.AnnotatedEndpoint$3.run(AnnotatedEndpoint.java:158)
		at io.undertow.websocket@2.3.0.Final//io.undertow.websockets.jsr.ServerWebSocketContainer$1.call(ServerWebSocketContainer.java:170)
		at io.undertow.websocket@2.3.0.Final//io.undertow.websockets.jsr.ServerWebSocketContainer$1.call(ServerWebSocketContainer.java:167)
		at io.undertow.servlet@2.3.0.Final//io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
		at org.wildfly.extension.undertow@27.0.0.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1435)
		at org.wildfly.extension.undertow@27.0.0.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1435)
		at org.wildfly.extension.undertow@27.0.0.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1435)
		at org.wildfly.extension.undertow@27.0.0.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1435)
		at io.undertow.websocket@2.3.0.Final//io.undertow.websockets.jsr.ServerWebSocketContainer.invokeEndpointMethod(ServerWebSocketContainer.java:618)
		at io.undertow.websocket@2.3.0.Final//io.undertow.websockets.jsr.ServerWebSocketContainer$6.run(ServerWebSocketContainer.java:604)
		at io.undertow.websocket@2.3.0.Final//io.undertow.websockets.jsr.OrderedExecutor$ExecutorTask.run(OrderedExecutor.java:67)
		at org.jboss.threads@2.4.0.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
		at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
		at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
		at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
		at org.jboss.xnio@3.8.8.Final//org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1282)
		at java.base/java.lang.Thread.run(Thread.java:833)

	19:20:23,440 INFO  [stdout] (default task-2) Received message: check if executor is still null: null

=> the backend loop for polling price cannot work since the new thread is not started successfully

**Comment by rxue** [comment]
**Analysis**

High similarity with https://developer.jboss.org/thread/277571

This might be related to the *Wildfly* server.

Based on the Java EE Platform specification: 

> The specifications for the different containers indicate which classes are considered container-managed classes; not all classes of a given type are necessarily managed by the container. 

*WebSocket* is the new feature in Java EE 7, and the annotation-based endpoint class is not *container-managed objects* in Wildfly server

=> **Solution:** turn the *WebSocket* endpoint into *container-managed object*

**Comment by rxue** [comment]
yet encountered **error**

	org.jboss.weld.contexts.ContextNotActiveException: WELD-001303: No active contexts for scope type jakarta.enterprise.context.RequestScoped
		at org.jboss.weld.core@5.1.0.Final//org.jboss.weld.manager.BeanManagerImpl.getContext(BeanManagerImpl.java:628)
		at org.jboss.weld.core@5.1.0.Final//org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.getIfExists(ContextualInstanceStrategy.java:89)
		at org.jboss.weld.core@5.1.0.Final//org.jboss.weld.bean.ContextualInstanceStrategy$CachingContextualInstanceStrategy.getIfExists(ContextualInstanceStrategy.java:164)
		at org.jboss.weld.core@5.1.0.Final//org.jboss.weld.bean.ContextualInstance.getIfExists(ContextualInstance.java:63)
		at org.jboss.weld.core@5.1.0.Final//org.jboss.weld.bean.proxy.ContextBeanInstance.getInstance(ContextBeanInstance.java:87)
		at org.jboss.weld.core@5.1.0.Final//org.jboss.weld.bean.proxy.ProxyMethodHandler.getInstance(ProxyMethodHandler.java:131)
		at deployment.investment.war//rx.investment.StockPriceMonitor$Proxy$_$$_WeldClientProxy.toString(Unknown Source)
		at java.base/java.util.Formatter$FormatSpecifier.printString(Formatter.java:3056)
		at java.base/java.util.Formatter$FormatSpecifier.print(Formatter.java:2933)
		at java.base/java.util.Formatter.format(Formatter.java:2689)
		at java.base/java.util.Formatter.format(Formatter.java:2625)
		at java.base/java.lang.String.format(String.java:4143)
		at org.jboss.logmanager@2.1.19.Final//org.jboss.logmanager.ExtLogRecord.formatRecord(ExtLogRecord.java:505)
		at org.jboss.logmanager@2.1.19.Final//org.jboss.logmanager.ExtLogRecord.getFormattedMessage(ExtLogRecord.java:468)
		at org.jboss.logmanager@2.1.19.Final//org.jboss.logmanager.formatters.Formatters$16.renderRaw(Formatters.java:737)
		at org.jboss.logmanager@2.1.19.Final//org.jboss.logmanager.formatters.Formatters$JustifyingFormatStep.render(Formatters.java:215)
		at org.jboss.logmanager@2.1.19.Final//org.jboss.logmanager.formatters.MultistepFormatter.format(MultistepFormatter.java:89)
		at org.jboss.logmanager@2.1.19.Final//org.jboss.logmanager.ExtFormatter.format(ExtFormatter.java:32)
		at org.jboss.logmanager@2.1.19.Final//org.jboss.logmanager.handlers.WriterHandler.doPublish(WriterHandler.java:46)
		at org.jboss.logmanager@2.1.19.Final//org.jboss.logmanager.ExtHandler.publish(ExtHandler.java:77)
		at org.jboss.logmanager@2.1.19.Final//org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:333)
		at org.jboss.logmanager@2.1.19.Final//org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:341)
		at org.jboss.logmanager@2.1.19.Final//org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:341)
		at org.jboss.logmanager@2.1.19.Final//org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:341)
		at org.jboss.logmanager@2.1.19.Final//org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:341)
		at org.jboss.logmanager@2.1.19.Final//org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:341)
		at org.jboss.logmanager@2.1.19.Final//org.jboss.logmanager.Logger.logRaw(Logger.java:852)
		at org.jboss.logmanager@2.1.19.Final//org.jboss.logmanager.Logger.log(Logger.java:804)
		at org.jboss.logging@3.4.3.Final//org.jboss.logging.JBossLogManagerLogger.doLogf(JBossLogManagerLogger.java:53)
		at org.jboss.logging@3.4.3.Final//org.jboss.logging.Logger.logf(Logger.java:2398)
		at io.undertow.core@2.3.0.Final//io.undertow.websockets.core.WebSocketLogger_$logger.unhandledErrorInAnnotatedEndpoint(WebSocketLogger_$logger.java:41)
		at io.undertow.websocket@2.3.0.Final//io.undertow.websockets.jsr.annotated.AnnotatedEndpoint.onError(AnnotatedEndpoint.java:242)
		at io.undertow.websocket@2.3.0.Final//io.undertow.websockets.jsr.annotated.AnnotatedEndpoint$3.run(AnnotatedEndpoint.java:160)
		at io.undertow.websocket@2.3.0.Final//io.undertow.websockets.jsr.ServerWebSocketContainer$1.call(ServerWebSocketContainer.java:170)
		at io.undertow.websocket@2.3.0.Final//io.undertow.websockets.jsr.ServerWebSocketContainer$1.call(ServerWebSocketContainer.java:167)
		at io.undertow.servlet@2.3.0.Final//io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
		at org.wildfly.extension.undertow@27.0.0.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1435)
		at org.wildfly.extension.undertow@27.0.0.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1435)
		at org.wildfly.extension.undertow@27.0.0.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1435)
		at org.wildfly.extension.undertow@27.0.0.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1435)
		at io.undertow.websocket@2.3.0.Final//io.undertow.websockets.jsr.ServerWebSocketContainer.invokeEndpointMethod(ServerWebSocketContainer.java:618)
		at io.undertow.websocket@2.3.0.Final//io.undertow.websockets.jsr.ServerWebSocketContainer$6.run(ServerWebSocketContainer.java:604)
		at io.undertow.websocket@2.3.0.Final//io.undertow.websockets.jsr.OrderedExecutor$ExecutorTask.run(OrderedExecutor.java:67)
		at org.jboss.threads@2.4.0.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
		at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
		at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
		at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
		at org.jboss.xnio@3.8.8.Final//org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1282)
		at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by rxue** [comment]
**Analysis**

The design of using `ManagedExecutorService` instance inside the endpoint POJO might be improper in that the *WebSocket* endpoint POJO is single-thread by nature
